Bookstore: connect to API
David-Kasilia/bookstore-with-react pull request #4
Opened 2022-09-21 15:20 UTC by David-Kasilia

### **To Highlight**

- Worked on the postman to make the necessary requests
- Used the axios and thunk to make API calls
- Installed axios and redux thunk
- Fetch the list from the bookstore API when the page loads
- Add and remove works the same way
![redux2](https://user-images.githubusercontent.com/83514256/191544311-4fcade05-f4f5-41af-8b44-48a608c18fdc.PNG)

2022-09-21 15:33 UTC, mateo951 requested changes
### Hi @David-Kasilia, 

Great job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-09-21 15:33 UTC, mateo951 commented on src/components/AddBook.js
>  const AddBook = () => {
Please be sure to use createAsyncThunk for creating thunk action creators as it is required in the guidelines 🤓

2022-09-21 15:33 UTC, mateo951 commented on src/components/AddBook.js
> +    const addNewBook = await axios.post(`${api}`, {
All [Bookstore API](https://www.notion.so/Bookstore-API-51ea269061f849118c65c0a53e88a739) calls are done with `fetch` OR `axios` ✔ Well done!

2022-09-21 15:36 UTC, David-Kasilia commented on src/components/AddBook.js
> +    const addNewBook = await axios.post(`${api}`, {
@mateo951 Hello, I would like to request if am working on both reviews or the first review.Thank you for your review

2022-09-22 00:14 UTC, mikethreels approved these changes
Hi David, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- good job following the instructions from the previous CR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 00:17 UTC, merged